extends: ['airbnb-base', 'prettier']
plugins: ['prettier']
rules:
  arrow-body-style: 0
  no-underscore-dangle: 0
  class-methods-use-this: 0
  camelcase: 0
  prettier/prettier: 'error'
env:
  commonjs: true
  es6: true
  node: true
  mocha: true
parserOptions:
  ecmaVersion: 2018
globals:
  __: true
  expect: true
  sinon: true
  Atomics: 'readonly'
  SharedArrayBuffer: 'readonly'
